name: Monitor mulesoft releases

on:
  workflow_dispatch:

jobs:
  mule-release:
    runs-on: ubuntu-latest
    steps:
      - uses: git-for-windows/rss-to-issues@v0.0.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feed: https://docs.mulesoft.com/releases.rss
          prefix: "[API Manager release]"
          character-limit: 255
          dry-run: true
          max-age: 72h
          labels: release
          title-pattern: /API Manager.*/i
          #content-pattern: /^API Manager$/
