name: Monitor mulesoft releases

on:
  schedule:
    # Run this Action every day at 7:00am PST (15:00 UTC)
    - cron: "00 15 * * *"
  workflow_dispatch:
  
jobs:
  mule-release:
    runs-on: ubuntu-latest
    steps:
      - uses: git-for-windows/rss-to-issues@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feed: https://docs.mulesoft.com/releases.rss
          prefix: "[Flex Gateway release]"
          character-limit: 5000
          max-age: 3d
          labels: release
          title-pattern: ^.*Anypoint Flex Gateway [0-9\.]*$
