name: Monitor mulesoft releases

on:
  workflow_dispatch:

jobs:
  mule-release:
    runs-on: ubuntu-latest
    steps:
      - uses: git-for-windows/rss-to-issues@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feed: https://docs.mulesoft.com/releases.rss
          prefix: "[API Manager release]"
          character-limit: 5000
          max-age: 3d
          labels: release
          title-pattern: /^.*API Manager/
          #content-pattern: /^API Manager$/
